controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    

diffbot_base_controller:
  ros__parameters:
    # type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.154 #0.152 #0.10 #重點參數，如果與實際不符合會導致激光雷達在建圖牆壁會因為機器人移動而著這動
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.0335 #0.015

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 30.0 #50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    #虛擬odom 依靠速度來確認里程計，適合模擬用，實體要關掉，因為要參考真的里程計
    #open_loop: true
    open_loop: false
    enable_odom_tf: true

    #新增的
    #odometry_topic: /odom
    publish_odom: true
    publish_odom_tf: true


    cmd_vel_timeout: 0.5

    command_interfaces: ["velocity"]  # 新增
    state_interfaces: ["position", "velocity"]  # 新增
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
